// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: src/proto/authorize.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "authorize";

/** Account status enum */
export enum AccountStatus {
  SUSPENDED = 0,
  REVIEWING = 1,
  APPROVED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

/** Account status enum */
export enum IAM {
  ROOT = 0,
  SUBUSER = 1,
  UNRECOGNIZED = -1,
}

/** User type enum */
export enum UserType {
  VESSEL_OWNER = 0,
  CHARTER = 1,
  TRUCKER = 2,
  CLEARANCE_AGENT = 3,
  STORAGE_TERMINAL = 4,
  STORAGE_WAREHOUSE = 5,
  CARGO_INSURANCE = 6,
  UNRECOGNIZED = -1,
}

/** Group policy message */
export enum GroupPolicy {
  ACCOUNTS = 0,
  DATA = 1,
  WIZARD = 2,
  FINANCE = 3,
  PROFILE = 4,
  REQUESTS = 5,
  FIND = 6,
  BOOKINGS = 7,
  DRIVERS = 8,
  FLEET = 9,
  WORKORDERS = 10,
  FIND_CARGO = 11,
  FIND_LOAD = 12,
  FIND_CLEARANCE = 13,
  FIND_STORAGE_TERMINAL = 14,
  FIND_STORAGE_WAREHOUSE = 15,
  STOWAGE_VESSEL_DETAILS = 16,
  STOWAGE_VESSEL_VOYAGE = 17,
  PERFORMANCE_MAIN_ENGINE = 18,
  PERFORMANCE_AUXILIARY_ENGINE = 19,
  UNRECOGNIZED = -1,
}

/** Request message containing user authorization details */
export interface AuthorizeRequest {
  accountStatus: AccountStatus;
  userType: UserType;
  iam: IAM;
  userId: string;
  groupPolicyId: string;
  menu: GroupPolicy;
}

/** Response message containing authorization status */
export interface AuthorizeResponse {
  statusCode: number;
  message?: string | undefined;
}

export const AUTHORIZE_PACKAGE_NAME = "authorize";

/** Service definition for authorization */

export interface AuthorizeServiceClient {
  /** Authorize user based on account status, user type, and permissions */

  authorizeUser(request: AuthorizeRequest): Observable<AuthorizeResponse>;
}

/** Service definition for authorization */

export interface AuthorizeServiceController {
  /** Authorize user based on account status, user type, and permissions */

  authorizeUser(
    request: AuthorizeRequest,
  ): Promise<AuthorizeResponse> | Observable<AuthorizeResponse> | AuthorizeResponse;
}

export function AuthorizeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authorizeUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthorizeService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthorizeService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTHORIZE_SERVICE_NAME = "AuthorizeService";
