// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: src/proto/subscription.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "subscription";

/** subscription/subscription.proto */

/** Enum for AccountStatus */
export enum AccountStatus {
  REVIEWING = 0,
  APPROVED = 1,
  SUSPENDED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

/** Enum for UserType */
export enum UserType {
  TRUCKER = 0,
  STORAGE_TERMINAL = 1,
  STORAGE_WAREHOUSE = 2,
  CLEARANCE_AGENT = 3,
  CARGO_INSURANCE = 4,
  VESSEL_OWNER = 5,
  CHARTER = 6,
  ADMIN = 7,
  UNRECOGNIZED = -1,
}

/** Enum for Subscribed Service */
export enum SubscribedService {
  STOWAGE = 0,
  ENGINE_PERFORMANCE = 1,
  UNRECOGNIZED = -1,
}

/** Request message with user payload and module */
export interface SubscriptionCheckRequest {
  /** The module name the user wants to access (SubscribedService enum as string) */
  module: SubscribedService;
  /** User payload */
  user: UserPayload | undefined;
}

/** Response message with authorization result */
export interface SubscriptionCheckResponse {
  isAuthorized: boolean;
  /** Optional message explaining why access is denied */
  message: string;
}

/** UserPayload message matching TPayload structure */
export interface UserPayload {
  accountStatus: AccountStatus;
  userType: UserType;
  /** "ROOT" or "SUBUSER" */
  iam: string;
  userId: string;
  groupPolicyId: string;
  /** Issued at (Unix timestamp) */
  iat: number;
  /** Expiration (Unix timestamp) */
  exp: number;
}

export const SUBSCRIPTION_PACKAGE_NAME = "subscription";

/** Define the SubscriptionCheck service */

export interface SubscriptionCheckServiceClient {
  checkAccess(request: SubscriptionCheckRequest): Observable<SubscriptionCheckResponse>;
}

/** Define the SubscriptionCheck service */

export interface SubscriptionCheckServiceController {
  checkAccess(
    request: SubscriptionCheckRequest,
  ): Promise<SubscriptionCheckResponse> | Observable<SubscriptionCheckResponse> | SubscriptionCheckResponse;
}

export function SubscriptionCheckServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkAccess"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SubscriptionCheckService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SubscriptionCheckService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SUBSCRIPTION_CHECK_SERVICE_NAME = "SubscriptionCheckService";
