// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: src/proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

/** user/user.proto */

/** Enum for UserType */
export enum UserType {
  TRUCKER = 0,
  STORAGE_TERMINAL = 1,
  STORAGE_WAREHOUSE = 2,
  CLEARANCE_AGENT = 3,
  CARGO_INSURANCE = 4,
  VESSEL_OWNER = 5,
  CHARTER = 6,
  ADMIN = 7,
  CONTRACTOR = 8,
  YARD_OWNER = 9,
  UNRECOGNIZED = -1,
}

/** Enum for AccountStatus */
export enum AccountStatus {
  REVIEWING = 0,
  APPROVED = 1,
  SUSPENDED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

/** Request message for login */
export interface LoginRequest {
  email: string;
  password: string;
  userType: UserType;
}

/** Response message for login */
export interface LoginResponse {
  token: string;
  user: UserResponse | undefined;
}

/** Request message to get user by ID */
export interface GetUserByIdRequest {
  userId: string;
}

/** Request message for signup */
export interface SignupRequest {
  name: string;
  email: string;
  password: string;
  userType: UserType;
}

/** Response message for signup */
export interface SignupResponse {
  success: boolean;
  message: string;
}

/** User info message */
export interface UserResponse {
  id: string;
  name: string;
  email: string;
  userType: UserType;
  accountStatus: AccountStatus;
  iam: string;
  /** Unix timestamp (creationDate) */
  createdAt: number;
}

export const USER_PACKAGE_NAME = "user";

/** Define the User service */

export interface UserServiceClient {
  login(request: LoginRequest): Observable<LoginResponse>;

  getUserById(request: GetUserByIdRequest): Observable<UserResponse>;

  signup(request: SignupRequest): Observable<SignupResponse>;
}

/** Define the User service */

export interface UserServiceController {
  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  getUserById(request: GetUserByIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  signup(request: SignupRequest): Promise<SignupResponse> | Observable<SignupResponse> | SignupResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "getUserById", "signup"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
