// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: src/proto/verify.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "verify";

/** verify/verify.proto */

/** Enum for AccountStatus */
export enum AccountStatus {
  REVIEWING = 0,
  APPROVED = 1,
  SUSPENDED = 2,
  REJECTED = 3,
  UNRECOGNIZED = -1,
}

/** Enum for UserType */
export enum UserType {
  TRUCKER = 0,
  STORAGE_TERMINAL = 1,
  STORAGE_WAREHOUSE = 2,
  CLEARANCE_AGENT = 3,
  CARGO_INSURANCE = 4,
  VESSEL_OWNER = 5,
  CHARTER = 6,
  ADMIN = 7,
  UNRECOGNIZED = -1,
}

/** Request message with a token */
export interface VerifyRequest {
  token: string;
}

/** Response message with the payload */
export interface VerifyResponse {
  payload:
    | Payload
    | undefined;
  /** Indicates if verification succeeded */
  success: boolean;
  /** Optional error message if verification fails */
  error: string;
}

/** Payload message matching TPayload */
export interface Payload {
  accountStatus: AccountStatus;
  userType: UserType;
  /** "ROOT" or "SUBUSER" */
  iam: string;
  userId: string;
  groupPolicyId: string;
  /** Issued at (Unix timestamp) */
  iat: number;
  /** Expiration (Unix timestamp) */
  exp: number;
}

export const VERIFY_PACKAGE_NAME = "verify";

/** Define the Verify service */

export interface VerifyServiceClient {
  verify(request: VerifyRequest): Observable<VerifyResponse>;
}

/** Define the Verify service */

export interface VerifyServiceController {
  verify(request: VerifyRequest): Promise<VerifyResponse> | Observable<VerifyResponse> | VerifyResponse;
}

export function VerifyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["verify"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("VerifyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("VerifyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VERIFY_SERVICE_NAME = "VerifyService";
